INSERT INTO book VALUES(1,'DBMS','JAN-2017','MCGRAW-HILL');
INSERT INTO book VALUES(2,'ADBMS','JUN-2016','MCGRAW-HILL');
INSERT INTO book VALUES(3,'CN','SEP-2016','PEARSON');
INSERT INTO book VALUES(4,'CG','SEP-2015','PLANETA');
INSERT INTO book VALUES(5,'OS','MAY-2016','PEARSON');