INSERT INTO book_authors VALUES(1,'NAVATHE');
INSERT INTO book_authors VALUES(2,'NAVATHE');
INSERT INTO book_authors VALUES(3,'TANENBAUM');
INSERT INTO book_authors VALUES(4,'EDWARD ANGEL');
INSERT INTO book_authors VALUES(5,'GALVIN');