INSERT INTO library_branch VALUES(10,'RR NAGAR','BANGALORE');
INSERT INTO library_branch VALUES(11,'RNSIT','BANGALORE');
INSERT INTO library_branch VALUES(12,'RAJAJI NAGAR','BANGALORE');
INSERT INTO library_branch VALUES(13,'NITTE','MANGALORE');
INSERT INTO library_branch VALUES(14,'MANIPAL','UDUPI');